### ISSUE TITLE
Dart 2.8 does not persist work with pop

### ISSUE THREAD

**Issue by jacksonw765** [fluttercommunity/persist_theme#4]
In the newest update of Flutter 1.17 / Dart 2.8 it looks there's an issue with persist_theme. When the user changes to dark mode or off dark mode, the theme is not persisted when pop() is called. 

For example:

MainScreen() => push to Settings() (change theme)

When you pop back to MainScreen it will show the original theme. Any ideas? It was working fine before the Flutter 1.17 update. 

I've attached a quick gif. 

![video](https://user-images.githubusercontent.com/13068724/81860931-765f8c00-9535-11ea-83b5-2ae1f1d5bcd6.gif)

**Comment by rodydavis** [comment]
Please test on the latest!

**Comment by rodydavis** [comment]
Also check the example with updated docs

**Comment by jacksonw765** [comment]
No luck, I implemented the changes yet when changing the theme and popping back to the previous screen the old theme is still applied.

**Comment by rodydavis** [comment]
Are you wrapping the material app with the theme builder?

<img width="351" alt="Screen Shot 2020-05-27 at 12 29 45 AM" src="https://user-images.githubusercontent.com/31253215/82990528-32e33400-9fb1-11ea-8f8b-bef2fced7524.png">

**Comment by jacksonw765** [comment]
Does this look correct? It worked fine before Dart 2.8.

```
return PersistTheme(
      model: ThemeModel(),
      builder: (context, model, child) {
        return HomeScreen();
      },
    );
```

In HomeScreen build I am getting the current theme by:
`final _theme = Provider.of<ThemeModel>(context, listen: true);`

It works fine when I replace pop with a push.

**Comment by rodydavis** [comment]
No it has to be above the materialapp or widgets app.

**Comment by jacksonw765** [comment]
Okay I added it above and still getting the same result. 

```
class MainScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return PersistTheme(
      model: ThemeModel(),
      builder: (context, model, child) {
        return MaterialApp(
          navigatorObservers: [
            FirebaseAnalyticsObserver(analytics: Helpers.analytics),
          ],
          debugShowCheckedModeBanner: false,
            theme: model.theme,
            home: child,
        );
      },
      child: HomeScreen(),
    );
  }
}
```

```
void main() {
  runApp(MainScreen());
}
```

**Comment by rodydavis** [comment]
Can you paste minimal code to reproduce?

**Comment by jacksonw765** [comment]
I put together a demo however the issue appears to be on my end. Thanks for your dedication to this plugin! Closing this issue.

**Comment by rodydavis** [comment]
You are so welcome!
